# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 11:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='add_date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 4, 23, 11, 11, 5, 199927, tzinfo=utc), editable=False, verbose_name='Add date'),
        ),
        migrations.AddField(
            model_name='token',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 23, 11, 11, 5, 200136, tzinfo=utc), editable=False, verbose_name='Update date'),
        ),
    ]
